### ISSUE TITLE
科技玩家 登录错误，不知道是不是因为使用了谷歌无限邮箱作为登录账号

### ISSUE THREAD

**Issue by Deleted-Account** [LinYuanovo/scripts#1]
根据脚本提示， 变量：kjwj='账号&密码'，分别用 邮箱 或 昵称 作为账号，跑脚本都无法登录
(实测用 昵称 作为 账号 来登录网站，会提示 用户名XXXXX未在本站点注册)

青龙中运行脚本后提示：

`账号[undefined]登录成功，现有积分：undefined
【开始查询签到状态】
TypeError: Cannot read properties of undefined (reading 'credit')
    at /ql/scripts/LinYuanovo_scripts/kjwj.js:180:39
    at /ql/scripts/LinYuanovo_scripts/kjwj.js:414:6904
    at processTicksAndRejections (node:internal/process/task_queues:96:5)`

(该repo的旧版科技玩家脚本也是一样的提示)

不知道是不是因为我用的谷歌无限邮箱注册的科技玩家
本来Gmail的账户是 aaa@gmail.com
无限邮箱 是 aaa+kejiwanjia@gmail.com
类似这样的，导致脚本无法登录

**Comment by LinYuanovo** [comment]
> 根据脚本提示， 变量：kjwj='账号&密码'，分别用 邮箱 或 昵称 作为账号，跑脚本都无法登录 (实测用 昵称 作为 账号 来登录网站，会提示 用户名XXXXX未在本站点注册)
> 
> 青龙中运行脚本后提示：
> 
> `账号[undefined]登录成功，现有积分：undefined 【开始查询签到状态】 TypeError: Cannot read properties of undefined (reading 'credit') at /ql/scripts/LinYuanovo_scripts/kjwj.js:180:39 at /ql/scripts/LinYuanovo_scripts/kjwj.js:414:6904 at processTicksAndRejections (node:internal/process/task_queues:96:5)`
> 
> (该repo的旧版科技玩家脚本也是一样的提示)
> 
> 不知道是不是因为我用的谷歌无限邮箱注册的科技玩家 本来Gmail的账户是 [aaa@gmail.com](mailto:aaa@gmail.com) 无限邮箱 是 [aaa+kejiwanjia@gmail.com](mailto:aaa+kejiwanjia@gmail.com) 类似这样的，导致脚本无法登录

你好，关于你反应的问题，请问你所用的邮箱如你所举例一样带有+号吗，如果是这样的话，你可以尝试将+替换成%2B

**Comment by Deleted-Account** [comment]
好的我试试，感谢回复
