### ISSUE TITLE
统一养茶做不了任务了

### ISSUE THREAD

**Issue by a1564471347** [LinYuanovo/scripts#3]
脚本失效了

**Comment by LinYuanovo** [comment]
你好，脚本是正常的，或许是token失效了

**Comment by a1564471347** [comment]
token重新抓的是一样的ck

**Comment by a1564471347** [comment]
重新抓了可以了，原来养茶token会过期

**Comment by Deleted-Account** [comment]
似乎过期很快啊，周末刚抓的token，周三还没到就失效了

**Comment by Deleted-Account** [comment]
周末抓的Token失效
```
【开始签到】
签到失败，原因是：undefined
【开始两个阅读】
阅读失败，原因是：undefined
阅读失败，原因是：undefined
【开始三个种植任务】
【开始两个关注任务】
关注失败
关注失败
【开始抽奖】
抽奖失败，可能是已无抽奖次数
抽奖失败，可能是已无抽奖次数
抽奖失败，可能是已无抽奖次数
```

重新抓了下Token，好像小程序更新了，
养茶的Token变长了好多， body也变长了，结构也不太一样

重抓的🐎运行后出错：


undefined:78

```
SyntaxError: Unexpected token { in JSON at position 1637
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (/ql/scripts/LinYuanovo_scripts/sendNotify.js:165:26)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1151:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/ql/scripts/LinYuanovo_scripts/tyyc.js:23:30)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)

Node.js v17.5.0
```

**Comment by Deleted-Account** [comment]
另一个号也重新抓了🐎，也跑不了

```
【开始签到】
签到失败，今日已签到
【开始两个阅读】
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /ql/data/scripts/LinYuanovo_scripts/tyyc.js:207:29
    at new Promise (<anonymous>)
    at doRead (/ql/data/scripts/LinYuanovo_scripts/tyyc.js:206:12)
    at /ql/data/scripts/LinYuanovo_scripts/tyyc.js:83:28
```
