### ISSUE TITLE
红旗智联报错

### ISSUE THREAD

**Issue by fengchenzhihun1** [LinYuanovo/scripts#4]
大佬好！红旗用青龙跑报错
【debug】===============这是 签到 返回data==============
undefined
SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at /ql/scripts/raw_main_hqzl.js:170:35
    at /ql/scripts/raw_main_hqzl.js:807:6904
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by LinYuanovo** [comment]
请检查你的ck是否正确？两个变量，且都只需要值
