### ISSUE TITLE
小米运动刷步 好像不能用了大佬

### ISSUE THREAD

**Issue by kkkkxl** [LinYuanovo/scripts#9]
开始接口1刷步
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at /ql/data/scripts/xmbs.js:106:36
    at /ql/data/scripts/xmbs.js:248:5837
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by kkkkxl** [comment]
打印了一下data  接口好像没了
![image](https://user-images.githubusercontent.com/37541028/188291554-bd6f2103-e77c-4834-b166-f23e1228317f.png)



<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>

**Comment by kkkkxl** [comment]
![image](https://user-images.githubusercontent.com/37541028/188291566-54c7cce9-a557-47e3-aab1-57b84552272c.png)

**Comment by kkkkxl** [comment]
直接使用第二个接口就好了 ,  但是第一个接口出异常 直接结束 不会走接口2
